# Generated by Django 3.0.4 on 2021-10-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211019_1601'),
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
    ]
