# Generated by Django 3.0.4 on 2021-10-20 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20211019_1612'),
        ('users', '0003_profile_address'),
    ]

    operations = [
    ]
