# Generated by Django 3.0.4 on 2021-10-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_auto_20211020_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='other',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'PL'), ('PACKED', 'PK'), ('SHIPPED', 'SH'), ('DELIVERED', 'DL'), ('CART', 'CA')], default='CA', max_length=200, null=True),
        ),
    ]
