# Generated by Django 3.0.4 on 2021-10-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0003_auto_20211020_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PL', 'PLACED'), ('PK', 'PACKED'), ('SH', 'SHIPPED'), ('DL', 'DELIVERED'), ('CA', 'CART')], default='CA', max_length=200, null=True),
        ),
    ]
