# Generated by Django 3.0.4 on 2021-10-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0005_cart'),
        ('ecomm', '0005_auto_20211020_1557'),
    ]

    operations = [
    ]
