# Generated by Django 3.2.8 on 2021-10-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0006_merge_20211020_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
