# Generated by Django 3.2.8 on 2021-10-21 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0007_auto_20211021_0345'),
        ('ecomm', '0008_alter_cart_order_item'),
    ]

    operations = [
    ]
