# Generated by Django 3.0.4 on 2021-10-21 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0008_alter_cart_order_item'),
        ('ecomm', '0007_auto_20211021_0345'),
    ]

    operations = [
    ]
