# Generated by Django 3.0.4 on 2021-10-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0009_merge_20211021_0404'),
        ('ecomm', '0010_auto_20211021_0956'),
    ]

    operations = [
    ]
